### ISSUE TITLE
Planning Phase: Play Hunt The Wumpus and Create ERD

### ISSUE THREAD

**Issue by AlexSanchez7x** [DmitryLandy/Hunt-The-Wumpus#12]
1. Play Hunt the Wumpus to better understand what we are developing.
2. Review the ERD to identify possible changes that need to be made.

3. 2/15/2021: Jim Receives Notes on the ERD and updates the ERD

**Comment by mister-dl** [comment]
Mine and Doug's is Completed in the DmitryBranch

**Comment by mister-dl** [comment]
ERD has been completed, revised, and understood. The flowchart was created based off of it.
