### ISSUE TITLE
Finish The Initial Game Outline

### ISSUE THREAD

**Issue by mister-dl** [DmitryLandy/Hunt-The-Wumpus#4]
# Initial Game Outline
---
Finish the [initial game outline](https://github.com/DmitryLandy/Hunt-The-Wumpus/blob/main/InitialOutline.md). This is done by taking the rules, interpret them, and create the outline based on it. 

@douglas-doniel
@alexsanchez7
@dakinwerneburg

**Comment by AlexSanchez7x** [comment]
Doug Completes Initial Outline
