### ISSUE TITLE
Choosing Roles

### ISSUE THREAD

**Issue by mister-dl** [DmitryLandy/Hunt-The-Wumpus#5]
# Choosing Roles
---
We need to decide on the roles for the project. The following are some of the possible roles:

- **Github Manager**: Manages Github merge requests
- **Programmer**: Creates the code
- **Unit Tester**: Tests the created code
- **Issue manager**: Assigning and managing the tickets and writing documentation

**Comment by AlexSanchez7x** [comment]
Programming Pairs
- Two coordinate time to work together on the code

Dakin, Scott
Dmitry, Doug
Jae, Jim
Phil, Alex

GitHub manager: Dmitry, Dakin, Jae, Phil.
Issue Manager: Alex
Program Manager: Rotating by Phase
